# Generated by Django 2.1.7 on 2019-03-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('main_title', models.CharField(blank=True, default='Dionis', max_length=64, null=True)),
                ('our_city', models.CharField(blank=True, default='Львов', max_length=64, null=True)),
                ('our_street', models.CharField(blank=True, default='Шевченко 24', max_length=64, null=True)),
                ('our_email', models.EmailField(blank=True, default='DionisVicinus@gmail.com', max_length=64, null=True)),
                ('our_inst', models.CharField(blank=True, default='D_i0Ni_S', max_length=64, null=True)),
                ('our_face', models.CharField(blank=True, default='DioVici', max_length=64, null=True)),
                ('super_action', models.IntegerField(default=0)),
                ('super_title', models.CharField(blank=True, default='f', max_length=64, null=True)),
                ('super_title_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
